import Head from 'next/head'
import Image from 'next/image'


// Components
import HomePage from '../components/containers/Home/index';
import {Box} from '@chakra-ui/react';
import Footer from '../components/containers/Footer/index';




export default function Home() {
  return (
  <>
  <Box background='black'>
      <Head>
        <title>The Lighthouse</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com"/>
<link href="https://fonts.googleapis.com/css2?family=VT323&display=swap" rel="stylesheet"/>


<link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com"/>
<link href="https://fonts.googleapis.com/css2?family=Press+Start+2P&family=VT323&display=swap" rel="stylesheet"/>
      </Head>
      <HomePage/>
      <Footer/>
      </Box>
    </>
  )
}


const styles = {
  container: {
    height: '100%',


  }
}